name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create dist directory
      run: mkdir dist

    - name: Copy icon to the dist folder
      run: |
        copy use.ico dist

    # Build python script into a standalone exe
    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        onefile: true

    - name: Upload EXE to Repository
      uses: actions/upload-artifact@v3
      with:
        name: USE
        path: build/main.exe
    
    - name: Create a ZIP archive
      shell: powershell
      run: Compress-Archive -Path build/main.exe -DestinationPath USE.zip

    # Checkout the repository again to push changes to a different repository
    - name: Checkout USEwebsite repository
      uses: actions/checkout@v4
      with:
        repository: SoftwareRat/USEwebsite
        ref: main
        path: USEwebsite

    # Add the USE.zip file to the Gajim folder
    - name: Add USE.zip to Gajim folder
      run: |
        cd USEwebsite
        copy ../USE.zip Gajim/
        git add Gajim/USE.zip

    # Commit the changes
    - name: Commit changes
      run: |
        cd USEwebsite
        git commit -m "Add USE.zip to Gajim folder"

    # Push changes to the repository
    - name: Push changes
      run: git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # Add your personal access token as a secret