name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --hidden-import requests --specpath ./dist main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: USE
        path: ./dist/  # Modify if your PyInstaller output folder is different